config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-kc/keycloak:
      branch: master
      repo: https://github.com/eosc-kc/keycloak.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-kc/keycloak git:
        commands:
        - /usr/bin/env sh .sqa/script.bronze_visionary_gull.sh
        container: qc.acc_polar_balanced_condor
  QC.Doc:
    repos:
      github.com/eosc-kc/keycloak find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cobalt_bright_emu.sh
        container: qc.doc_umber_shrewd_crane
      github.com/eosc-kc/keycloak git:
        commands:
        - /usr/bin/env sh .sqa/script.pine_bubbly_dhole.sh
        container: qc.doc_plum_adventurous_antelope
      github.com/eosc-kc/keycloak markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.mahogany_loyal_lynx.sh
        container: qc.doc_jet_serene_platypus
  QC.Lic:
    repos:
      github.com/eosc-kc/keycloak licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cardamom_mindful_kangaroo.sh
        container: qc.lic_cerulean_audacious_alligator
  QC.Sec:
    repos:
      github.com/eosc-kc/keycloak bandit:
        commands:
        - /usr/bin/env sh .sqa/script.mauve_hopeful_tapir.sh
        container: qc.sec_navy_eager_narwhal
  QC.Sty:
    repos:
      github.com/eosc-kc/keycloak checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.prussian_calm_shark.sh
        container: qc.sty_strawberry_warm_kraken
      github.com/eosc-kc/keycloak flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ginger_dramatic_wolf.sh
        container: qc.sty_peach_warm_butterfly
      github.com/eosc-kc/keycloak hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.butter_impulsive_gorilla.sh
        container: qc.sty_incarnadine_understanding_reindeer
      github.com/eosc-kc/keycloak jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.rosewater_imaginative_quokka.sh
        container: qc.sty_aquamarine_outgoing_pegasus
  QC.Uni:
    repos:
      github.com/eosc-kc/keycloak pytest:
        commands:
        - /usr/bin/env sh .sqa/script.goldenrod_mindful_mongoose.sh
        container: qc.uni_turquoise_affectionate_hyena
  QC.Ver:
    repos:
      github.com/eosc-kc/keycloak get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.indigo_graceful_gorilla.sh
        container: qc.ver_cream_curious_wolverine
timeout: 5400
